package fan.company.springbootpermissionandauthorization.entity;


public enum Huquq {

    //USER UCHUN PERMISSION
    ADD_USER,
    EDIT_USER,
    DELETE_USER,
    VIEW_USER,

    //LAVOZIM (ROLE) UCHUN PERMISSION
    ADD_LAVOZIM,
    EDIT_LAVOZIM,
    DELETE_LAVOZIM,
    VIEW_LAVOZIM,

    //POST (MAQOLA) UCHUN PERMISSION
    ADD_POST,
    EDIT_POST,
    DELETE_POST,

    //COMMENT (KOMENTARIYA) UCHUN PERMISSION
    ADD_COMMENT,
    EDIT_COMMENT,
    DELETE_MY_COMMENT,
    DELETE_COMMENT,





}
